name: Deploy Doxygen Documentation
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Redirect HTML â†ª
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'docs'
          file: 'index.html'
          content: |
            Hello
            World

      - name: Doxygen ğŸˆ 
        uses: mattnotmitt/doxygen-action@v1

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.

