name: Deploy Doxygen Documentation
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Doxygen ğŸˆ 
        uses: mattnotmitt/doxygen-action@v1
        
      - uses: "finnp/create-file-action@master"
            env:
              FILE_NAME: "docs/index.html"
              FILE_DATA: "test"

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.

